# Generated by Django 3.2.9 on 2021-12-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=100)),
                ('locationAddress', models.CharField(max_length=100)),
                ('locationCity', models.CharField(max_length=100)),
                ('locationState', models.CharField(max_length=100)),
                ('tableSize', models.CharField(max_length=100)),
                ('tableBrand', models.CharField(max_length=100)),
                ('tableCondition', models.CharField(max_length=100)),
                ('cueCondition', models.CharField(max_length=100)),
                ('hasChalk', models.BooleanField(default=False)),
                ('vibe', models.CharField(max_length=100)),
                ('newFriends', models.CharField(max_length=100)),
            ],
        ),
    ]
