# Generated by Django 3.2.9 on 2021-12-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
