# Generated by Django 3.2.9 on 2021-12-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_api', '0002_rename_places_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='hasChalk',
        ),
    ]
