# Generated by Django 3.2.9 on 2021-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_api', '0003_remove_place_haschalk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='vibe',
            field=models.CharField(max_length=300),
        ),
    ]
